import "./globals.css";

export const metadata = {
  title: "Malcolms next app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}

// import React from "react";
// import "./globals.css";
// import { FC, ReactNode } from "react";

// import Head from "next/head";
// import { Html } from "next/document";

// const Layout: FC<{ children?: ReactNode }> = ({ children }) => {
//   return (
//     <Html>
//       {/* <Head></Head> */}
//       <body>{children}</body>
//     </Html>
//   );
// };

// export default Layout;
